name: Check form submissions
on:
  schedule:
    - cron: '12 * * * *'
  repository_dispatch:
    types: [manual-run]
jobs:
  check_form_submissions:
    runs-on: ghcr.io/jimpick/sp-kyc-tools
    steps:
      - run: node sync_google_form.mjs
  finish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Write date to log and commit
        run: |
          set -euo pipefail
          set -x
          git config --global user.name 'check-form-submissions'
          git config --global user.email 'robot@jimpick.com'
          echo "Date: $(date)" >> dates.log
          git add dates.log
          git commit -m 'Wrote date to log from GitHub Action'
          git pull
          git push
