name: Check form submissions
on:
  schedule:
    - cron: '12 * * * *'
  repository_dispatch:
    types: [manual-run]
jobs:
  check_form_submissions:
    runs-on: ubuntu-latest
    steps:
      - name: Sync submissions from Google Form
        id: new_responses
        uses: jimpick/sp-kyc-tools/download-google-form-responses@HEAD
        with:
          form-id: 1z0Ja5VidknDfngLkbAr10Z20VaKZPf2q4n5x6Bgm5v8
          credentials-json: ${{ secrets.CREDENTIALS_JSON }}
      - name: Upload form responses
        uses: actions/upload-artifact@v3
        with:
          name: google-form-responses
          path: /tmp/output/google-form-responses.json
      - name: Get the output time
        run: echo "The time was ${{ steps.new_responses.outputs.time }}"
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Write date to log and commit
        run: |
          set -euo pipefail
          set -x
          git config --global user.name 'check-form-submissions'
          git config --global user.email 'robot@jimpick.com'
          echo "Date: $(date)" >> dates.log
          git add dates.log
          git commit -m 'Wrote date to log from GitHub Action'
          git pull
          git push
